# Markdown
markdown: kramdown

# Permalinks
permalink: /posts/:title

# Setup
title:               Meta Hunch
url:                 https://metahunch.github.io/
baseurl:             ''

# About/contact
author:
  name:              Xintong Li
  url:               https://znculee.github.io/
  email:             znculee@gmail.com

# Collections
collections:
  collections: # name of a collection
    output: true
    permalink: /:path
